# Generated by Django 6.0.3 on 2026-03-09 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_cinemahall_movie_moviesession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesession',
            old_name='showtime',
            new_name='show_time',
        ),
    ]
